### ISSUE TITLE
AttributeError: 'API' object has no attribute 'sso_token'

### ISSUE THREAD

**Issue by therockmandolinist** [eve-val/evelink#230]
Encountered this error upon recent install. Not sure what it's about. 

<img width="475" alt="screen shot 2016-06-13 at 11 43 42" src="https://cloud.githubusercontent.com/assets/9020453/16019098/25196b4a-315c-11e6-8ba9-7f64b86e7dc0.png">

**Comment by ayust** [comment]
Hm. In normal operation however that error shouldn't be possible (`self.sso_token` is set in `API.__init__`, [here](https://github.com/eve-val/evelink/blob/master/evelink/api.py#L236)).

Are you by chance pickling or otherwise serializing API objects into some sort of long-term storage, then trying to read them back out? If there were an API object from an older version of the library that was then trying to be read into the newer version of the library, that could cause an error like that.

**Comment by ayust** [comment]
If you're not serializing/pickling API objects (or some object that contains an API object), then I'd probably need to know more about the context in which the error is occurring - i.e. exactly what call is generating it.

**Comment by therockmandolinist** [comment]
Yep, I was pickling objects – solved!

**Comment by ayust** [comment]
As a side note, I'd recommend not pickling `API` objects - they aren't designed to be long-lifed.

`APIResult` objects are fine to pickle if you want to save the results of calls.

**Comment by therockmandolinist** [comment]
@ayust I'm just recently learning about all of this, thanks... I noticed results get automatically cached, could you explain how that works?

Also, I was curious what sqlite3.Binary is (used in evelink/cache/sqlite.py) – I can't seem to find any documentation for it anywhere (including the sqlite3 module page on python3 docs)

**Comment by ayust** [comment]
Sure!

Every response from the EVE API includes a "cache until" timestamp which indicates how long a client should wait before requesting the same thing again (because the value will only update every so often). By default the EVELink library uses an in-memory cache to remember the results from calls to the API. It automatically stores the results for as long as the EVE API recommends.

However, because it's an in-memory cache, whenever your script/program exits, the cache is lost. Since some API calls can have cache times 15 minutes, an hour, or even more, you often want to be able to preserve the cached values across invocations of a script or restarts of a program. That's where the disk-based caches come in.

The best disk-based cache option is probably the `SqliteCache` - it uses a SQLite file-based database to store the cached values on disk. To use it, just create a SqliteCache object and pass it as the `cache` argument to the `API` object constructor. Then EVELink will store all of its cached API call results in the path you provided.

As for `sqlite3.Binary` - that's just one of the data types that SQLite offers when storing values in its database file. Using the "binary" type means that it will treat the data it receives as raw binary data rather than trying to format it as text, which is good, since we're storing binary pickled objects in it.

**Comment by therockmandolinist** [comment]
Woah, you answered questions I made, questions I had but didn't make, and questions I didn't even know I had. Thanks for the thorough explanation!
